// Code generated by the FlatBuffers compiler. DO NOT EDIT.

package store

import (
	flatbuffers "github.com/google/flatbuffers/go"
)

type Product struct {
	_tab flatbuffers.Table
}

func GetRootAsProduct(buf []byte, offset flatbuffers.UOffsetT) *Product {
	n := flatbuffers.GetUOffsetT(buf[offset:])
	x := &Product{}
	x.Init(buf, n+offset)
	return x
}

func FinishProductBuffer(builder *flatbuffers.Builder, offset flatbuffers.UOffsetT) {
	builder.Finish(offset)
}

func GetSizePrefixedRootAsProduct(buf []byte, offset flatbuffers.UOffsetT) *Product {
	n := flatbuffers.GetUOffsetT(buf[offset+flatbuffers.SizeUint32:])
	x := &Product{}
	x.Init(buf, n+offset+flatbuffers.SizeUint32)
	return x
}

func FinishSizePrefixedProductBuffer(builder *flatbuffers.Builder, offset flatbuffers.UOffsetT) {
	builder.FinishSizePrefixed(offset)
}

func (rcv *Product) Init(buf []byte, i flatbuffers.UOffsetT) {
	rcv._tab.Bytes = buf
	rcv._tab.Pos = i
}

func (rcv *Product) Table() flatbuffers.Table {
	return rcv._tab
}

func (rcv *Product) Id() int32 {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(4))
	if o != 0 {
		return rcv._tab.GetInt32(o + rcv._tab.Pos)
	}
	return 0
}

func (rcv *Product) MutateId(n int32) bool {
	return rcv._tab.MutateInt32Slot(4, n)
}

func (rcv *Product) Name() []byte {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(6))
	if o != 0 {
		return rcv._tab.ByteVector(o + rcv._tab.Pos)
	}
	return nil
}

func (rcv *Product) Description() []byte {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(8))
	if o != 0 {
		return rcv._tab.ByteVector(o + rcv._tab.Pos)
	}
	return nil
}

func (rcv *Product) Price() float64 {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(10))
	if o != 0 {
		return rcv._tab.GetFloat64(o + rcv._tab.Pos)
	}
	return 0.0
}

func (rcv *Product) MutatePrice(n float64) bool {
	return rcv._tab.MutateFloat64Slot(10, n)
}

func (rcv *Product) Amount() int32 {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(12))
	if o != 0 {
		return rcv._tab.GetInt32(o + rcv._tab.Pos)
	}
	return 0
}

func (rcv *Product) MutateAmount(n int32) bool {
	return rcv._tab.MutateInt32Slot(12, n)
}

func ProductStart(builder *flatbuffers.Builder) {
	builder.StartObject(5)
}
func ProductAddId(builder *flatbuffers.Builder, id int32) {
	builder.PrependInt32Slot(0, id, 0)
}
func ProductAddName(builder *flatbuffers.Builder, name flatbuffers.UOffsetT) {
	builder.PrependUOffsetTSlot(1, flatbuffers.UOffsetT(name), 0)
}
func ProductAddDescription(builder *flatbuffers.Builder, description flatbuffers.UOffsetT) {
	builder.PrependUOffsetTSlot(2, flatbuffers.UOffsetT(description), 0)
}
func ProductAddPrice(builder *flatbuffers.Builder, price float64) {
	builder.PrependFloat64Slot(3, price, 0.0)
}
func ProductAddAmount(builder *flatbuffers.Builder, amount int32) {
	builder.PrependInt32Slot(4, amount, 0)
}
func ProductEnd(builder *flatbuffers.Builder) flatbuffers.UOffsetT {
	return builder.EndObject()
}
